/**
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package com.microsoft.bot.schema.models;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * A response containing a resource.
 */
public class ConversationResourceResponse {
    /**
     * ID of the Activity (if sent).
     */
    @JsonProperty(value = "activityId")
    private String activityId;

    /**
     * Service endpoint where operations concerning the conversation may be
     * performed.
     */
    @JsonProperty(value = "serviceUrl")
    private String serviceUrl;

    /**
     * Id of the resource.
     */
    @JsonProperty(value = "id")
    private String id;

    /**
     * Get the activityId value.
     *
     * @return the activityId value
     */
    public String activityId() {
        return this.activityId;
    }

    /**
     * Set the activityId value.
     *
     * @param activityId the activityId value to set
     * @return the ConversationResourceResponse object itself.
     */
    public ConversationResourceResponse withActivityId(String activityId) {
        this.activityId = activityId;
        return this;
    }

    /**
     * Get the serviceUrl value.
     *
     * @return the serviceUrl value
     */
    public String serviceUrl() {
        return this.serviceUrl;
    }

    /**
     * Set the serviceUrl value.
     *
     * @param serviceUrl the serviceUrl value to set
     * @return the ConversationResourceResponse object itself.
     */
    public ConversationResourceResponse withServiceUrl(String serviceUrl) {
        this.serviceUrl = serviceUrl;
        return this;
    }

    /**
     * Get the id value.
     *
     * @return the id value
     */
    public String id() {
        return this.id;
    }

    /**
     * Set the id value.
     *
     * @param id the id value to set
     * @return the ConversationResourceResponse object itself.
     */
    public ConversationResourceResponse withId(String id) {
        this.id = id;
        return this;
    }

}
