/**
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package com.microsoft.bot.schema.models;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * An object relating to a particular point in a conversation.
 */
public class ConversationReference {
    /**
     * (Optional) ID of the activity to refer to.
     */
    @JsonProperty(value = "activityId")
    private String activityId;

    /**
     * (Optional) User participating in this conversation.
     */
    @JsonProperty(value = "user")
    private ChannelAccount user;

    /**
     * Bot participating in this conversation.
     */
    @JsonProperty(value = "bot")
    private ChannelAccount bot;

    /**
     * Conversation reference.
     */
    @JsonProperty(value = "conversation")
    private ConversationAccount conversation;

    /**
     * Channel ID.
     */
    @JsonProperty(value = "channelId")
    private String channelId;

    /**
     * Service endpoint where operations concerning the referenced conversation
     * may be performed.
     */
    @JsonProperty(value = "serviceUrl")
    private String serviceUrl;

    /**
     * Get the activityId value.
     *
     * @return the activityId value
     */
    public String activityId() {
        return this.activityId;
    }

    /**
     * Set the activityId value.
     *
     * @param activityId the activityId value to set
     * @return the ConversationReference object itself.
     */
    public ConversationReference withActivityId(String activityId) {
        this.activityId = activityId;
        return this;
    }

    /**
     * Get the user value.
     *
     * @return the user value
     */
    public ChannelAccount user() {
        return this.user;
    }

    /**
     * Set the user value.
     *
     * @param user the user value to set
     * @return the ConversationReference object itself.
     */
    public ConversationReference withUser(ChannelAccount user) {
        this.user = user;
        return this;
    }

    /**
     * Get the bot value.
     *
     * @return the bot value
     */
    public ChannelAccount bot() {
        return this.bot;
    }

    /**
     * Set the bot value.
     *
     * @param bot the bot value to set
     * @return the ConversationReference object itself.
     */
    public ConversationReference withBot(ChannelAccount bot) {
        this.bot = bot;
        return this;
    }

    /**
     * Get the conversation value.
     *
     * @return the conversation value
     */
    public ConversationAccount conversation() {
        return this.conversation;
    }

    /**
     * Set the conversation value.
     *
     * @param conversation the conversation value to set
     * @return the ConversationReference object itself.
     */
    public ConversationReference withConversation(ConversationAccount conversation) {
        this.conversation = conversation;
        return this;
    }

    /**
     * Get the channelId value.
     *
     * @return the channelId value
     */
    public String channelId() {
        return this.channelId;
    }

    /**
     * Set the channelId value.
     *
     * @param channelId the channelId value to set
     * @return the ConversationReference object itself.
     */
    public ConversationReference withChannelId(String channelId) {
        this.channelId = channelId;
        return this;
    }

    /**
     * Get the serviceUrl value.
     *
     * @return the serviceUrl value
     */
    public String serviceUrl() {
        return this.serviceUrl;
    }

    /**
     * Set the serviceUrl value.
     *
     * @param serviceUrl the serviceUrl value to set
     * @return the ConversationReference object itself.
     */
    public ConversationReference withServiceUrl(String serviceUrl) {
        this.serviceUrl = serviceUrl;
        return this;
    }

}
