/**
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package com.microsoft.bot.schema.models;

import java.util.List;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Parameters for creating a new conversation.
 */
public class ConversationParameters {
    /**
     * IsGroup.
     */
    @JsonProperty(value = "isGroup")
    private Boolean isGroup;

    /**
     * The bot address for this conversation.
     */
    @JsonProperty(value = "bot")
    private ChannelAccount bot;

    /**
     * Members to add to the conversation.
     */
    @JsonProperty(value = "members")
    private List<ChannelAccount> members;

    /**
     * (Optional) Topic of the conversation (if supported by the channel).
     */
    @JsonProperty(value = "topicName")
    private String topicName;

    /**
     * (Optional) The tenant ID in which the conversation should be created.
     */
    @JsonProperty(value = "tenantId")
    private String tenantId;

    /**
     * (Optional) When creating a new conversation, use this activity as the
     * intial message to the conversation.
     */
    @JsonProperty(value = "activity")
    private Activity activity;

    /**
     * Channel specific payload for creating the conversation.
     */
    @JsonProperty(value = "channelData")
    private Object channelData;

    /**
     * Get the isGroup value.
     *
     * @return the isGroup value
     */
    public Boolean isGroup() {
        return this.isGroup;
    }

    /**
     * Set the isGroup value.
     *
     * @param isGroup the isGroup value to set
     * @return the ConversationParameters object itself.
     */
    public ConversationParameters withIsGroup(Boolean isGroup) {
        this.isGroup = isGroup;
        return this;
    }

    /**
     * Get the bot value.
     *
     * @return the bot value
     */
    public ChannelAccount bot() {
        return this.bot;
    }

    /**
     * Set the bot value.
     *
     * @param bot the bot value to set
     * @return the ConversationParameters object itself.
     */
    public ConversationParameters withBot(ChannelAccount bot) {
        this.bot = bot;
        return this;
    }

    /**
     * Get the members value.
     *
     * @return the members value
     */
    public List<ChannelAccount> members() {
        return this.members;
    }

    /**
     * Set the members value.
     *
     * @param members the members value to set
     * @return the ConversationParameters object itself.
     */
    public ConversationParameters withMembers(List<ChannelAccount> members) {
        this.members = members;
        return this;
    }

    /**
     * Get the topicName value.
     *
     * @return the topicName value
     */
    public String topicName() {
        return this.topicName;
    }

    /**
     * Set the topicName value.
     *
     * @param topicName the topicName value to set
     * @return the ConversationParameters object itself.
     */
    public ConversationParameters withTopicName(String topicName) {
        this.topicName = topicName;
        return this;
    }

    /**
     * Get the activity value.
     *
     * @return the activity value
     */
    public Activity activity() {
        return this.activity;
    }

    /**
     * Set the activity value.
     *
     * @param activity the activity value to set
     * @return the ConversationParameters object itself.
     */
    public ConversationParameters withActivity(Activity activity) {
        this.activity = activity;
        return this;
    }

    /**
     * Get the channelData value.
     *
     * @return the channelData value
     */
    public Object channelData() {
        return this.channelData;
    }

    /**
     * Set the channelData value.
     *
     * @param channelData the channelData value to set
     * @return the ConversationParameters object itself.
     */
    public ConversationParameters withChannelData(Object channelData) {
        this.channelData = channelData;
        return this;
    }

    /**
     * Gets tenantId
     */
    public String tenantId(){
        return this.tenantId;
    }

    /**
     * Sets tenantId
     */
    public ConversationParameters withTenantId(String tenantId){
        this.tenantId = tenantId;
        return this;
    }
}
