/**
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package com.microsoft.bot.schema.models;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Defines values for EndOfConversationCodes.
 */
public enum EndOfConversationCodes {
    /** Enum value unknown. */
    UNKNOWN("unknown"),

    /** Enum value completedSuccessfully. */
    COMPLETED_SUCCESSFULLY("completedSuccessfully"),

    /** Enum value userCancelled. */
    USER_CANCELLED("userCancelled"),

    /** Enum value botTimedOut. */
    BOT_TIMED_OUT("botTimedOut"),

    /** Enum value botIssuedInvalidMessage. */
    BOT_ISSUED_INVALID_MESSAGE("botIssuedInvalidMessage"),

    /** Enum value channelFailed. */
    CHANNEL_FAILED("channelFailed");

    /** The actual serialized value for a EndOfConversationCodes instance. */
    private String value;

    EndOfConversationCodes(String value) {
        this.value = value;
    }

    /**
     * Parses a serialized value to a EndOfConversationCodes instance.
     *
     * @param value the serialized value to parse.
     * @return the parsed EndOfConversationCodes object, or null if unable to parse.
     */
    @JsonCreator
    public static EndOfConversationCodes fromString(String value) {
        EndOfConversationCodes[] items = EndOfConversationCodes.values();
        for (EndOfConversationCodes item : items) {
            if (item.toString().equalsIgnoreCase(value)) {
                return item;
            }
        }
        return null;
    }

    @JsonValue
    @Override
    public String toString() {
        return this.value;
    }
}
