/**
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package com.microsoft.bot.schema.models;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Object representing inner http error.
 */
public class InnerHttpError {
    /**
     * HttpStatusCode from failed request.
     */
    @JsonProperty(value = "statusCode")
    private int statusCode;

    /**
     * Body from failed request.
     */
    @JsonProperty(value = "body")
    private Object body;

    /**
     * Gets HttpStatusCode from failed request.
     *
     * @return the statusCode value
     */
    public int statusCode() {
        return this.statusCode;
    }

    /**
     * Sets HttpStatusCode from failed request.
     *
     * @param activities the activities value to set
     * @return the InnerHttpError object itself.
     */
    public InnerHttpError withStatusCode(int statusCode) {
        this.statusCode = statusCode;
        return this;
    }

    /**
     * Gets Body from failed request.
     */
    public Object body(){
        return this.body;
    }

    /**
     * Sets Body from failed request.
     * @param body The body to set
     */
    public InnerHttpError withBody(Object body){
        this.body = body;
        return this;
    }
}
