/**
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package com.microsoft.bot.schema.models;

import java.util.List;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Page of members
 */
public class PagedMembersResult {

    @JsonProperty(value = "continuationToken")
    private String continuationToken;

    /**
     * List of members in this conversation.
     */
    @JsonProperty(value = "members")
    private List<ChannelAccount> members;

    /**
     * Gets paging token
     */
    public String continuationToken(){
        return this.continuationToken;
    }

    /**
     * Sets paging token
     *
     * @return the PagedMembersResult object itself.
     */
    public PagedMembersResult withContinuationToken(String continuationToken){
        this.continuationToken = continuationToken;
        return this;
    }

    /**
     * Gets the Channel Accounts.
     *
     * @return the members value
     */
    public List<ChannelAccount> members() {
        return this.members;
    }

    /**
     * Sets the Channel Accounts.
     *
     * @param members the members value to set
     * @return the PagedMembersResult object itself.
     */
    public PagedMembersResult withMembers(List<ChannelAccount> members) {
        this.members = members;
        return this;
    }
}
