/**
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package com.microsoft.bot.schema.models;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Indicates what the payment request is for and the value asked for.
 */
public class PaymentItem {
    /**
     * Human-readable description of the item.
     */
    @JsonProperty(value = "label")
    private String label;

    /**
     * Monetary amount for the item.
     */
    @JsonProperty(value = "amount")
    private PaymentCurrencyAmount amount;

    /**
     * When set to true this flag means that the amount field is not final.
     */
    @JsonProperty(value = "pending")
    private Boolean pending;

    /**
     * Get the label value.
     *
     * @return the label value
     */
    public String label() {
        return this.label;
    }

    /**
     * Set the label value.
     *
     * @param label the label value to set
     * @return the PaymentItem object itself.
     */
    public PaymentItem withLabel(String label) {
        this.label = label;
        return this;
    }

    /**
     * Get the amount value.
     *
     * @return the amount value
     */
    public PaymentCurrencyAmount amount() {
        return this.amount;
    }

    /**
     * Set the amount value.
     *
     * @param amount the amount value to set
     * @return the PaymentItem object itself.
     */
    public PaymentItem withAmount(PaymentCurrencyAmount amount) {
        this.amount = amount;
        return this;
    }

    /**
     * Get the pending value.
     *
     * @return the pending value
     */
    public Boolean pending() {
        return this.pending;
    }

    /**
     * Set the pending value.
     *
     * @param pending the pending value to set
     * @return the PaymentItem object itself.
     */
    public PaymentItem withPending(Boolean pending) {
        this.pending = pending;
        return this;
    }

}
