/**
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package com.microsoft.bot.schema.models;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Supplies monetary amounts.
 */
public class PaymentCurrencyAmount {
    /**
     * A currency identifier.
     */
    @JsonProperty(value = "currency")
    private String currency;

    /**
     * Decimal monetary value.
     */
    @JsonProperty(value = "value")
    private String value;

    /**
     * Currency system.
     */
    @JsonProperty(value = "currencySystem")
    private String currencySystem;

    /**
     * Get the currency value.
     *
     * @return the currency value
     */
    public String currency() {
        return this.currency;
    }

    /**
     * Set the currency value.
     *
     * @param currency the currency value to set
     * @return the PaymentCurrencyAmount object itself.
     */
    public PaymentCurrencyAmount withCurrency(String currency) {
        this.currency = currency;
        return this;
    }

    /**
     * Get the value value.
     *
     * @return the value value
     */
    public String value() {
        return this.value;
    }

    /**
     * Set the value value.
     *
     * @param value the value value to set
     * @return the PaymentCurrencyAmount object itself.
     */
    public PaymentCurrencyAmount withValue(String value) {
        this.value = value;
        return this;
    }

    /**
     * Get the currencySystem value.
     *
     * @return the currencySystem value
     */
    public String currencySystem() {
        return this.currencySystem;
    }

    /**
     * Set the currencySystem value.
     *
     * @param currencySystem the currencySystem value to set
     * @return the PaymentCurrencyAmount object itself.
     */
    public PaymentCurrencyAmount withCurrencySystem(String currencySystem) {
        this.currencySystem = currencySystem;
        return this;
    }

}
