/**
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package com.microsoft.bot.schema.models;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Payload delivered when completing a payment request.
 */
public class PaymentRequestComplete {
    /**
     * Payment request ID.
     */
    @JsonProperty(value = "id")
    private String id;

    /**
     * Initial payment request.
     */
    @JsonProperty(value = "paymentRequest")
    private PaymentRequest paymentRequest;

    /**
     * Corresponding payment response.
     */
    @JsonProperty(value = "paymentResponse")
    private PaymentResponse paymentResponse;

    /**
     * Get the id value.
     *
     * @return the id value
     */
    public String id() {
        return this.id;
    }

    /**
     * Set the id value.
     *
     * @param id the id value to set
     * @return the PaymentRequestComplete object itself.
     */
    public PaymentRequestComplete withId(String id) {
        this.id = id;
        return this;
    }

    /**
     * Get the paymentRequest value.
     *
     * @return the paymentRequest value
     */
    public PaymentRequest paymentRequest() {
        return this.paymentRequest;
    }

    /**
     * Set the paymentRequest value.
     *
     * @param paymentRequest the paymentRequest value to set
     * @return the PaymentRequestComplete object itself.
     */
    public PaymentRequestComplete withPaymentRequest(PaymentRequest paymentRequest) {
        this.paymentRequest = paymentRequest;
        return this;
    }

    /**
     * Get the paymentResponse value.
     *
     * @return the paymentResponse value
     */
    public PaymentResponse paymentResponse() {
        return this.paymentResponse;
    }

    /**
     * Set the paymentResponse value.
     *
     * @param paymentResponse the paymentResponse value to set
     * @return the PaymentRequestComplete object itself.
     */
    public PaymentRequestComplete withPaymentResponse(PaymentResponse paymentResponse) {
        this.paymentResponse = paymentResponse;
        return this;
    }

}
