/**
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package com.microsoft.bot.schema.models;

import java.util.List;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * A request to make a payment.
 */
public class PaymentRequest {
    /**
     * ID of this payment request.
     */
    @JsonProperty(value = "id")
    private String id;

    /**
     * Allowed payment methods for this request.
     */
    @JsonProperty(value = "methodData")
    private List<PaymentMethodData> methodData;

    /**
     * Details for this request.
     */
    @JsonProperty(value = "details")
    private PaymentDetails details;

    /**
     * Provides information about the options desired for the payment request.
     */
    @JsonProperty(value = "options")
    private PaymentOptions options;

    /**
     * Expiration for this request, in ISO 8601 duration format (e.g., 'P1D').
     */
    @JsonProperty(value = "expires")
    private String expires;

    /**
     * Get the id value.
     *
     * @return the id value
     */
    public String id() {
        return this.id;
    }

    /**
     * Set the id value.
     *
     * @param id the id value to set
     * @return the PaymentRequest object itself.
     */
    public PaymentRequest withId(String id) {
        this.id = id;
        return this;
    }

    /**
     * Get the methodData value.
     *
     * @return the methodData value
     */
    public List<PaymentMethodData> methodData() {
        return this.methodData;
    }

    /**
     * Set the methodData value.
     *
     * @param methodData the methodData value to set
     * @return the PaymentRequest object itself.
     */
    public PaymentRequest withMethodData(List<PaymentMethodData> methodData) {
        this.methodData = methodData;
        return this;
    }

    /**
     * Get the details value.
     *
     * @return the details value
     */
    public PaymentDetails details() {
        return this.details;
    }

    /**
     * Set the details value.
     *
     * @param details the details value to set
     * @return the PaymentRequest object itself.
     */
    public PaymentRequest withDetails(PaymentDetails details) {
        this.details = details;
        return this;
    }

    /**
     * Get the options value.
     *
     * @return the options value
     */
    public PaymentOptions options() {
        return this.options;
    }

    /**
     * Set the options value.
     *
     * @param options the options value to set
     * @return the PaymentRequest object itself.
     */
    public PaymentRequest withOptions(PaymentOptions options) {
        this.options = options;
        return this;
    }

    /**
     * Get the expires value.
     *
     * @return the expires value
     */
    public String expires() {
        return this.expires;
    }

    /**
     * Set the expires value.
     *
     * @param expires the expires value to set
     * @return the PaymentRequest object itself.
     */
    public PaymentRequest withExpires(String expires) {
        this.expires = expires;
        return this;
    }

}
