/**
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package com.microsoft.bot.schema.models;

import java.util.List;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Address within a Payment Request.
 */
public class PaymentAddress {
    /**
     * This is the CLDR (Common Locale Data Repository) region code. For
     * example, US, GB, CN, or JP.
     */
    @JsonProperty(value = "country")
    private String country;

    /**
     * This is the most specific part of the address. It can include, for
     * example, a street name, a house number, apartment number, a rural
     * delivery route, descriptive instructions, or a post office box number.
     */
    @JsonProperty(value = "addressLine")
    private List<String> addressLine;

    /**
     * This is the top level administrative subdivision of the country. For
     * example, this can be a state, a province, an oblast, or a prefecture.
     */
    @JsonProperty(value = "region")
    private String region;

    /**
     * This is the city/town portion of the address.
     */
    @JsonProperty(value = "city")
    private String city;

    /**
     * This is the dependent locality or sublocality within a city. For
     * example, used for neighborhoods, boroughs, districts, or UK dependent
     * localities.
     */
    @JsonProperty(value = "dependentLocality")
    private String dependentLocality;

    /**
     * This is the postal code or ZIP code, also known as PIN code in India.
     */
    @JsonProperty(value = "postalCode")
    private String postalCode;

    /**
     * This is the sorting code as used in, for example, France.
     */
    @JsonProperty(value = "sortingCode")
    private String sortingCode;

    /**
     * This is the BCP-47 language code for the address. It's used to determine
     * the field separators and the order of fields when formatting the address
     * for display.
     */
    @JsonProperty(value = "languageCode")
    private String languageCode;

    /**
     * This is the organization, firm, company, or institution at this address.
     */
    @JsonProperty(value = "organization")
    private String organization;

    /**
     * This is the name of the recipient or contact person.
     */
    @JsonProperty(value = "recipient")
    private String recipient;

    /**
     * This is the phone number of the recipient or contact person.
     */
    @JsonProperty(value = "phone")
    private String phone;

    /**
     * Get the country value.
     *
     * @return the country value
     */
    public String country() {
        return this.country;
    }

    /**
     * Set the country value.
     *
     * @param country the country value to set
     * @return the PaymentAddress object itself.
     */
    public PaymentAddress withCountry(String country) {
        this.country = country;
        return this;
    }

    /**
     * Get the addressLine value.
     *
     * @return the addressLine value
     */
    public List<String> addressLine() {
        return this.addressLine;
    }

    /**
     * Set the addressLine value.
     *
     * @param addressLine the addressLine value to set
     * @return the PaymentAddress object itself.
     */
    public PaymentAddress withAddressLine(List<String> addressLine) {
        this.addressLine = addressLine;
        return this;
    }

    /**
     * Get the region value.
     *
     * @return the region value
     */
    public String region() {
        return this.region;
    }

    /**
     * Set the region value.
     *
     * @param region the region value to set
     * @return the PaymentAddress object itself.
     */
    public PaymentAddress withRegion(String region) {
        this.region = region;
        return this;
    }

    /**
     * Get the city value.
     *
     * @return the city value
     */
    public String city() {
        return this.city;
    }

    /**
     * Set the city value.
     *
     * @param city the city value to set
     * @return the PaymentAddress object itself.
     */
    public PaymentAddress withCity(String city) {
        this.city = city;
        return this;
    }

    /**
     * Get the dependentLocality value.
     *
     * @return the dependentLocality value
     */
    public String dependentLocality() {
        return this.dependentLocality;
    }

    /**
     * Set the dependentLocality value.
     *
     * @param dependentLocality the dependentLocality value to set
     * @return the PaymentAddress object itself.
     */
    public PaymentAddress withDependentLocality(String dependentLocality) {
        this.dependentLocality = dependentLocality;
        return this;
    }

    /**
     * Get the postalCode value.
     *
     * @return the postalCode value
     */
    public String postalCode() {
        return this.postalCode;
    }

    /**
     * Set the postalCode value.
     *
     * @param postalCode the postalCode value to set
     * @return the PaymentAddress object itself.
     */
    public PaymentAddress withPostalCode(String postalCode) {
        this.postalCode = postalCode;
        return this;
    }

    /**
     * Get the sortingCode value.
     *
     * @return the sortingCode value
     */
    public String sortingCode() {
        return this.sortingCode;
    }

    /**
     * Set the sortingCode value.
     *
     * @param sortingCode the sortingCode value to set
     * @return the PaymentAddress object itself.
     */
    public PaymentAddress withSortingCode(String sortingCode) {
        this.sortingCode = sortingCode;
        return this;
    }

    /**
     * Get the languageCode value.
     *
     * @return the languageCode value
     */
    public String languageCode() {
        return this.languageCode;
    }

    /**
     * Set the languageCode value.
     *
     * @param languageCode the languageCode value to set
     * @return the PaymentAddress object itself.
     */
    public PaymentAddress withLanguageCode(String languageCode) {
        this.languageCode = languageCode;
        return this;
    }

    /**
     * Get the organization value.
     *
     * @return the organization value
     */
    public String organization() {
        return this.organization;
    }

    /**
     * Set the organization value.
     *
     * @param organization the organization value to set
     * @return the PaymentAddress object itself.
     */
    public PaymentAddress withOrganization(String organization) {
        this.organization = organization;
        return this;
    }

    /**
     * Get the recipient value.
     *
     * @return the recipient value
     */
    public String recipient() {
        return this.recipient;
    }

    /**
     * Set the recipient value.
     *
     * @param recipient the recipient value to set
     * @return the PaymentAddress object itself.
     */
    public PaymentAddress withRecipient(String recipient) {
        this.recipient = recipient;
        return this;
    }

    /**
     * Get the phone value.
     *
     * @return the phone value
     */
    public String phone() {
        return this.phone;
    }

    /**
     * Set the phone value.
     *
     * @param phone the phone value to set
     * @return the PaymentAddress object itself.
     */
    public PaymentAddress withPhone(String phone) {
        this.phone = phone;
        return this;
    }

}
