/**
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package com.microsoft.bot.schema.models;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Result from a completed payment request.
 */
public class PaymentRequestCompleteResult {
    /**
     * Result of the payment request completion.
     */
    @JsonProperty(value = "result")
    private String result;

    /**
     * Get the result value.
     *
     * @return the result value
     */
    public String result() {
        return this.result;
    }

    /**
     * Set the result value.
     *
     * @param result the result value to set
     * @return the PaymentRequestCompleteResult object itself.
     */
    public PaymentRequestCompleteResult withResult(String result) {
        this.result = result;
        return this;
    }

}
