/**
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package com.microsoft.bot.schema.models;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Indicates whether the semantic action is starting, continuing, or done.
 */
public enum SemanticActionStates {
    /** Enum value start. */
    START("start"),

    /** Enum value continue. */
    CONTINUE("continue"),

    /** Enum value done. */
    DONE("done");


    /** The actual serialized value for a SemanticActionStates instance. */
    private String value;

    SemanticActionStates(String value) {
        this.value = value;
    }

    /**
     * Parses a serialized value to a ActivityTypes instance.
     *
     * @param value the serialized value to parse.
     * @return the parsed ActivityTypes object, or null if unable to parse.
     */
    @JsonCreator
    public static SemanticActionStates fromString(String value) {
        SemanticActionStates[] items = SemanticActionStates.values();
        for (SemanticActionStates item : items) {
            if (item.toString().equalsIgnoreCase(value)) {
                return item;
            }
        }
        return null;
    }

    @JsonValue
    @Override
    public String toString() {
        return this.value;
    }
}
