/**
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package com.microsoft.bot.connector.implementation;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Attachment data.
 */
public class AttachmentDataInner {
    /**
     * Content-Type of the attachment.
     */
    @JsonProperty(value = "type")
    private String type;

    /**
     * Name of the attachment.
     */
    @JsonProperty(value = "name")
    private String name;

    /**
     * Attachment content.
     */
    @JsonProperty(value = "originalBase64")
    private byte[] originalBase64;

    /**
     * Attachment thumbnail.
     */
    @JsonProperty(value = "thumbnailBase64")
    private byte[] thumbnailBase64;

    /**
     * Get the type value.
     *
     * @return the type value
     */
    public String type() {
        return this.type;
    }

    /**
     * Set the type value.
     *
     * @param type the type value to set
     * @return the AttachmentDataInner object itself.
     */
    public AttachmentDataInner withType(String type) {
        this.type = type;
        return this;
    }

    /**
     * Get the name value.
     *
     * @return the name value
     */
    public String name() {
        return this.name;
    }

    /**
     * Set the name value.
     *
     * @param name the name value to set
     * @return the AttachmentDataInner object itself.
     */
    public AttachmentDataInner withName(String name) {
        this.name = name;
        return this;
    }

    /**
     * Get the originalBase64 value.
     *
     * @return the originalBase64 value
     */
    public byte[] originalBase64() {
        return this.originalBase64;
    }

    /**
     * Set the originalBase64 value.
     *
     * @param originalBase64 the originalBase64 value to set
     * @return the AttachmentDataInner object itself.
     */
    public AttachmentDataInner withOriginalBase64(byte[] originalBase64) {
        this.originalBase64 = originalBase64;
        return this;
    }

    /**
     * Get the thumbnailBase64 value.
     *
     * @return the thumbnailBase64 value
     */
    public byte[] thumbnailBase64() {
        return this.thumbnailBase64;
    }

    /**
     * Set the thumbnailBase64 value.
     *
     * @param thumbnailBase64 the thumbnailBase64 value to set
     * @return the AttachmentDataInner object itself.
     */
    public AttachmentDataInner withThumbnailBase64(byte[] thumbnailBase64) {
        this.thumbnailBase64 = thumbnailBase64;
        return this;
    }

}
