/**
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package com.microsoft.bot.connector.implementation;

import java.util.List;
import com.microsoft.bot.connector.AttachmentView;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Metdata for an attachment.
 */
public class AttachmentInfoInner {
    /**
     * Name of the attachment.
     */
    @JsonProperty(value = "name")
    private String name;

    /**
     * ContentType of the attachment.
     */
    @JsonProperty(value = "type")
    private String type;

    /**
     * attachment views.
     */
    @JsonProperty(value = "views")
    private List<AttachmentView> views;

    /**
     * Get the name value.
     *
     * @return the name value
     */
    public String name() {
        return this.name;
    }

    /**
     * Set the name value.
     *
     * @param name the name value to set
     * @return the AttachmentInfoInner object itself.
     */
    public AttachmentInfoInner withName(String name) {
        this.name = name;
        return this;
    }

    /**
     * Get the type value.
     *
     * @return the type value
     */
    public String type() {
        return this.type;
    }

    /**
     * Set the type value.
     *
     * @param type the type value to set
     * @return the AttachmentInfoInner object itself.
     */
    public AttachmentInfoInner withType(String type) {
        this.type = type;
        return this;
    }

    /**
     * Get the views value.
     *
     * @return the views value
     */
    public List<AttachmentView> views() {
        return this.views;
    }

    /**
     * Set the views value.
     *
     * @param views the views value to set
     * @return the AttachmentInfoInner object itself.
     */
    public AttachmentInfoInner withViews(List<AttachmentView> views) {
        this.views = views;
        return this;
    }

}
