/**
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package com.microsoft.bot.connector.implementation;

import java.util.List;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Parameters for creating a new conversation.
 */
public class ConversationParametersInner {
    /**
     * IsGroup.
     */
    @JsonProperty(value = "isGroup")
    private Boolean isGroup;

    /**
     * The bot address for this conversation.
     */
    @JsonProperty(value = "bot")
    private ChannelAccountInner bot;

    /**
     * Members to add to the conversation.
     */
    @JsonProperty(value = "members")
    private List<ChannelAccountInner> members;

    /**
     * (Optional) Topic of the conversation (if supported by the channel).
     */
    @JsonProperty(value = "topicName")
    private String topicName;

    /**
     * (Optional) When creating a new conversation, use this activity as the
     * intial message to the conversation.
     */
    @JsonProperty(value = "activity")
    private ActivityInner activity;

    /**
     * Channel specific payload for creating the conversation.
     */
    @JsonProperty(value = "channelData")
    private Object channelData;

    /**
     * Get the isGroup value.
     *
     * @return the isGroup value
     */
    public Boolean isGroup() {
        return this.isGroup;
    }

    /**
     * Set the isGroup value.
     *
     * @param isGroup the isGroup value to set
     * @return the ConversationParametersInner object itself.
     */
    public ConversationParametersInner withIsGroup(Boolean isGroup) {
        this.isGroup = isGroup;
        return this;
    }

    /**
     * Get the bot value.
     *
     * @return the bot value
     */
    public ChannelAccountInner bot() {
        return this.bot;
    }

    /**
     * Set the bot value.
     *
     * @param bot the bot value to set
     * @return the ConversationParametersInner object itself.
     */
    public ConversationParametersInner withBot(ChannelAccountInner bot) {
        this.bot = bot;
        return this;
    }

    /**
     * Get the members value.
     *
     * @return the members value
     */
    public List<ChannelAccountInner> members() {
        return this.members;
    }

    /**
     * Set the members value.
     *
     * @param members the members value to set
     * @return the ConversationParametersInner object itself.
     */
    public ConversationParametersInner withMembers(List<ChannelAccountInner> members) {
        this.members = members;
        return this;
    }

    /**
     * Get the topicName value.
     *
     * @return the topicName value
     */
    public String topicName() {
        return this.topicName;
    }

    /**
     * Set the topicName value.
     *
     * @param topicName the topicName value to set
     * @return the ConversationParametersInner object itself.
     */
    public ConversationParametersInner withTopicName(String topicName) {
        this.topicName = topicName;
        return this;
    }

    /**
     * Get the activity value.
     *
     * @return the activity value
     */
    public ActivityInner activity() {
        return this.activity;
    }

    /**
     * Set the activity value.
     *
     * @param activity the activity value to set
     * @return the ConversationParametersInner object itself.
     */
    public ConversationParametersInner withActivity(ActivityInner activity) {
        this.activity = activity;
        return this;
    }

    /**
     * Get the channelData value.
     *
     * @return the channelData value
     */
    public Object channelData() {
        return this.channelData;
    }

    /**
     * Set the channelData value.
     *
     * @param channelData the channelData value to set
     * @return the ConversationParametersInner object itself.
     */
    public ConversationParametersInner withChannelData(Object channelData) {
        this.channelData = channelData;
        return this;
    }

}
