/**
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package com.microsoft.bot.connector.implementation;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * A response containing a resource ID.
 */
public class ResourceResponseInner {
    /**
     * Id of the resource.
     */
    @JsonProperty(value = "id")
    private String id;

    /**
     * Get the id value.
     *
     * @return the id value
     */
    public String id() {
        return this.id;
    }

    /**
     * Set the id value.
     *
     * @param id the id value to set
     * @return the ResourceResponseInner object itself.
     */
    public ResourceResponseInner withId(String id) {
        this.id = id;
        return this;
    }

}
