/**
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 * <p>
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package com.microsoft.bot.connector.teams;

import com.microsoft.bot.schema.teams.ConversationList;
import com.microsoft.bot.schema.teams.TeamDetails;

import java.util.concurrent.CompletableFuture;

/**
 * Teams operations.
 */
public interface TeamsOperations {
    /**
     * Fetches channel list for a given team.
     * 
     * @param teamId The team id.
     * @return A ConversationList object.
     */
    CompletableFuture<ConversationList> fetchChannelList(String teamId);

    /**
     * Fetches details related to a team.
     * 
     * @param teamId The team id.
     * @return The TeamDetails
     */
    CompletableFuture<TeamDetails> fetchTeamDetails(String teamId);
}
