/**
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package com.microsoft.bot.schema.models;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Defines values for ActivityImportance.
 */
public enum ActivityImportance {
    /** Enum value low. */
    LOW("low"),

    /** Enum value normal. */
    NORMAL("normal"),

    /** Enum value high. */
    HIGH("high");

    /** The actual serialized value for a ActivityImportance instance. */
    private String value;

    ActivityImportance(String value) {
        this.value = value;
    }

    /**
     * Parses a serialized value to a ActivityImportance instance.
     *
     * @param value the serialized value to parse.
     * @return the parsed ActivityImportance object, or null if unable to parse.
     */
    @JsonCreator
    public static ActivityImportance fromString(String value) {
        ActivityImportance[] items = ActivityImportance.values();
        for (ActivityImportance item : items) {
            if (item.toString().equalsIgnoreCase(value)) {
                return item;
            }
        }
        return null;
    }

    @JsonValue
    @Override
    public String toString() {
        return this.value;
    }
}
