/**
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package com.microsoft.bot.schema.models;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Defines action types for clickable buttons.
 */
public enum ActionTypes {
    /** Enum value openUrl. */
    OPEN_URL("openUrl"),

    /** Enum value imBack. */
    IM_BACK("imBack"),

    /** Enum value postBack. */
    POST_BACK("postBack"),

    /** Enum value playAudio. */
    PLAY_AUDIO("playAudio"),

    /** Enum value playVideo. */
    PLAY_VIDEO("playVideo"),

    /** Enum value showImage. */
    SHOW_IMAGE("showImage"),

    /** Enum value downloadFile. */
    DOWNLOAD_FILE("downloadFile"),

    /** Enum value signin. */
    SIGNIN("signin"),

    /** Enum value call. */
    CALL("call"),

    /** Enum value payment. */
    PAYMENT("payment"),

    /** Enum value messageBack. */
    MESSAGE_BACK("messageBack");

    /** The actual serialized value for a ActionTypes instance. */
    private String value;

    ActionTypes(String value) {
        this.value = value;
    }

    /**
     * Parses a serialized value to a ActionTypes instance.
     *
     * @param value the serialized value to parse.
     * @return the parsed ActionTypes object, or null if unable to parse.
     */
    @JsonCreator
    public static ActionTypes fromString(String value) {
        ActionTypes[] items = ActionTypes.values();
        for (ActionTypes item : items) {
            if (item.toString().equalsIgnoreCase(value)) {
                return item;
            }
        }
        return null;
    }

    @JsonValue
    @Override
    public String toString() {
        return this.value;
    }
}
