/**
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package com.microsoft.bot.schema.models;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Defines values for AttachmentLayoutTypes.
 */
public enum AttachmentLayoutTypes {
    /** Enum value list. */
    LIST("list"),

    /** Enum value carousel. */
    CAROUSEL("carousel");

    /** The actual serialized value for a AttachmentLayoutTypes instance. */
    private String value;

    AttachmentLayoutTypes(String value) {
        this.value = value;
    }

    /**
     * Parses a serialized value to a AttachmentLayoutTypes instance.
     *
     * @param value the serialized value to parse.
     * @return the parsed AttachmentLayoutTypes object, or null if unable to parse.
     */
    @JsonCreator
    public static AttachmentLayoutTypes fromString(String value) {
        AttachmentLayoutTypes[] items = AttachmentLayoutTypes.values();
        for (AttachmentLayoutTypes item : items) {
            if (item.toString().equalsIgnoreCase(value)) {
                return item;
            }
        }
        return null;
    }

    @JsonValue
    @Override
    public String toString() {
        return this.value;
    }
}
