/**
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package com.microsoft.bot.schema.models;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Attachment View name and size.
 */
public class AttachmentView {
    /**
     * Content type of the attachment.
     */
    @JsonProperty(value = "viewId")
    private String viewId;

    /**
     * Name of the attachment.
     */
    @JsonProperty(value = "size")
    private Integer size;

    /**
     * Get the viewId value.
     *
     * @return the viewId value
     */
    public String viewId() {
        return this.viewId;
    }

    /**
     * Set the viewId value.
     *
     * @param viewId the viewId value to set
     * @return the AttachmentView object itself.
     */
    public AttachmentView withViewId(String viewId) {
        this.viewId = viewId;
        return this;
    }

    /**
     * Get the size value.
     *
     * @return the size value
     */
    public Integer size() {
        return this.size;
    }

    /**
     * Set the size value.
     *
     * @param size the size value to set
     * @return the AttachmentView object itself.
     */
    public AttachmentView withSize(Integer size) {
        this.size = size;
        return this;
    }

}
