/**
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package com.microsoft.bot.schema.models;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * A clickable action.
 */
public class CardAction {
    /**
     * The type of action implemented by this button. Possible values include:
     * 'openUrl', 'imBack', 'postBack', 'playAudio', 'playVideo', 'showImage',
     * 'downloadFile', 'signin', 'call', 'payment', 'messageBack'.
     */
    @JsonProperty(value = "type")
    private ActionTypes type;

    /**
     * Text description which appears on the button.
     */
    @JsonProperty(value = "title")
    private String title;

    /**
     * Image URL which will appear on the button, next to text label.
     */
    @JsonProperty(value = "image")
    private String image;

    /**
     * Text for this action.
     */
    @JsonProperty(value = "text")
    private String text;

    /**
     * (Optional) text to display in the chat feed if the button is clicked.
     */
    @JsonProperty(value = "displayText")
    private String displayText;

    /**
     * Supplementary parameter for action. Content of this property depends on
     * the ActionType.
     */
    @JsonProperty(value = "value")
    private Object value;

    /**
     * Get the type value.
     *
     * @return the type value
     */
    public ActionTypes type() {
        return this.type;
    }

    /**
     * Set the type value.
     *
     * @param type the type value to set
     * @return the CardAction object itself.
     */
    public CardAction withType(ActionTypes type) {
        this.type = type;
        return this;
    }

    /**
     * Get the title value.
     *
     * @return the title value
     */
    public String title() {
        return this.title;
    }

    /**
     * Set the title value.
     *
     * @param title the title value to set
     * @return the CardAction object itself.
     */
    public CardAction withTitle(String title) {
        this.title = title;
        return this;
    }

    /**
     * Get the image value.
     *
     * @return the image value
     */
    public String image() {
        return this.image;
    }

    /**
     * Set the image value.
     *
     * @param image the image value to set
     * @return the CardAction object itself.
     */
    public CardAction withImage(String image) {
        this.image = image;
        return this;
    }

    /**
     * Get the text value.
     *
     * @return the text value
     */
    public String text() {
        return this.text;
    }

    /**
     * Set the text value.
     *
     * @param text the text value to set
     * @return the CardAction object itself.
     */
    public CardAction withText(String text) {
        this.text = text;
        return this;
    }

    /**
     * Get the displayText value.
     *
     * @return the displayText value
     */
    public String displayText() {
        return this.displayText;
    }

    /**
     * Set the displayText value.
     *
     * @param displayText the displayText value to set
     * @return the CardAction object itself.
     */
    public CardAction withDisplayText(String displayText) {
        this.displayText = displayText;
        return this;
    }

    /**
     * Get the value value.
     *
     * @return the value value
     */
    public Object value() {
        return this.value;
    }

    /**
     * Set the value value.
     *
     * @param value the value value to set
     * @return the CardAction object itself.
     */
    public CardAction withValue(Object value) {
        this.value = value;
        return this;
    }

}
