/**
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package com.microsoft.bot.schema.models;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Defines values for InstallationUpdateActionTypes.
 */
public enum InstallationUpdateActionTypes {
    /** Enum value add. */
    ADD("add"),

    /** Enum value remove. */
    REMOVE("remove");

    /** The actual serialized value for a InstallationUpdateActionTypes instance. */
    private String value;

    InstallationUpdateActionTypes(String value) {
        this.value = value;
    }

    /**
     * Parses a serialized value to a InstallationUpdateActionTypes instance.
     *
     * @param value the serialized value to parse.
     * @return the parsed InstallationUpdateActionTypes object, or null if unable to parse.
     */
    @JsonCreator
    public static InstallationUpdateActionTypes fromString(String value) {
        InstallationUpdateActionTypes[] items = InstallationUpdateActionTypes.values();
        for (InstallationUpdateActionTypes item : items) {
            if (item.toString().equalsIgnoreCase(value)) {
                return item;
            }
        }
        return null;
    }

    @JsonValue
    @Override
    public String toString() {
        return this.value;
    }
}
