/**
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package com.microsoft.bot.schema.models;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Supplementary parameter for media events.
 */
public class MediaEventValue {
    /**
     * Callback parameter specified in the Value field of the MediaCard that
     * originated this event.
     */
    @JsonProperty(value = "cardValue")
    private Object cardValue;

    /**
     * Get the cardValue value.
     *
     * @return the cardValue value
     */
    public Object cardValue() {
        return this.cardValue;
    }

    /**
     * Set the cardValue value.
     *
     * @param cardValue the cardValue value to set
     * @return the MediaEventValue object itself.
     */
    public MediaEventValue withCardValue(Object cardValue) {
        this.cardValue = cardValue;
        return this;
    }

}
