/**
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package com.microsoft.bot.schema.models;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Defines values for MessageReactionTypes.
 */
public enum MessageReactionTypes {
    /** Enum value like. */
    LIKE("like"),

    /** Enum value plusOne. */
    PLUS_ONE("plusOne");

    /** The actual serialized value for a MessageReactionTypes instance. */
    private String value;

    MessageReactionTypes(String value) {
        this.value = value;
    }

    /**
     * Parses a serialized value to a MessageReactionTypes instance.
     *
     * @param value the serialized value to parse.
     * @return the parsed MessageReactionTypes object, or null if unable to parse.
     */
    @JsonCreator
    public static MessageReactionTypes fromString(String value) {
        MessageReactionTypes[] items = MessageReactionTypes.values();
        for (MessageReactionTypes item : items) {
            if (item.toString().equalsIgnoreCase(value)) {
                return item;
            }
        }
        return null;
    }

    @JsonValue
    @Override
    public String toString() {
        return this.value;
    }
}
