/**
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package com.microsoft.bot.schema.models;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Describes a shipping option.
 */
public class PaymentShippingOption {
    /**
     * String identifier used to reference this PaymentShippingOption.
     */
    @JsonProperty(value = "id")
    private String id;

    /**
     * Human-readable description of the item.
     */
    @JsonProperty(value = "label")
    private String label;

    /**
     * Contains the monetary amount for the item.
     */
    @JsonProperty(value = "amount")
    private PaymentCurrencyAmount amount;

    /**
     * Indicates whether this is the default selected PaymentShippingOption.
     */
    @JsonProperty(value = "selected")
    private Boolean selected;

    /**
     * Get the id value.
     *
     * @return the id value
     */
    public String id() {
        return this.id;
    }

    /**
     * Set the id value.
     *
     * @param id the id value to set
     * @return the PaymentShippingOption object itself.
     */
    public PaymentShippingOption withId(String id) {
        this.id = id;
        return this;
    }

    /**
     * Get the label value.
     *
     * @return the label value
     */
    public String label() {
        return this.label;
    }

    /**
     * Set the label value.
     *
     * @param label the label value to set
     * @return the PaymentShippingOption object itself.
     */
    public PaymentShippingOption withLabel(String label) {
        this.label = label;
        return this;
    }

    /**
     * Get the amount value.
     *
     * @return the amount value
     */
    public PaymentCurrencyAmount amount() {
        return this.amount;
    }

    /**
     * Set the amount value.
     *
     * @param amount the amount value to set
     * @return the PaymentShippingOption object itself.
     */
    public PaymentShippingOption withAmount(PaymentCurrencyAmount amount) {
        this.amount = amount;
        return this;
    }

    /**
     * Get the selected value.
     *
     * @return the selected value
     */
    public Boolean selected() {
        return this.selected;
    }

    /**
     * Set the selected value.
     *
     * @param selected the selected value to set
     * @return the PaymentShippingOption object itself.
     */
    public PaymentShippingOption withSelected(Boolean selected) {
        this.selected = selected;
        return this;
    }

}
