/**
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package com.microsoft.bot.schema.models;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * An update to a payment request.
 */
public class PaymentRequestUpdate {
    /**
     * ID for the payment request to update.
     */
    @JsonProperty(value = "id")
    private String id;

    /**
     * Update payment details.
     */
    @JsonProperty(value = "details")
    private PaymentDetails details;

    /**
     * Updated shipping address.
     */
    @JsonProperty(value = "shippingAddress")
    private PaymentAddress shippingAddress;

    /**
     * Updated shipping options.
     */
    @JsonProperty(value = "shippingOption")
    private String shippingOption;

    /**
     * Get the id value.
     *
     * @return the id value
     */
    public String id() {
        return this.id;
    }

    /**
     * Set the id value.
     *
     * @param id the id value to set
     * @return the PaymentRequestUpdate object itself.
     */
    public PaymentRequestUpdate withId(String id) {
        this.id = id;
        return this;
    }

    /**
     * Get the details value.
     *
     * @return the details value
     */
    public PaymentDetails details() {
        return this.details;
    }

    /**
     * Set the details value.
     *
     * @param details the details value to set
     * @return the PaymentRequestUpdate object itself.
     */
    public PaymentRequestUpdate withDetails(PaymentDetails details) {
        this.details = details;
        return this;
    }

    /**
     * Get the shippingAddress value.
     *
     * @return the shippingAddress value
     */
    public PaymentAddress shippingAddress() {
        return this.shippingAddress;
    }

    /**
     * Set the shippingAddress value.
     *
     * @param shippingAddress the shippingAddress value to set
     * @return the PaymentRequestUpdate object itself.
     */
    public PaymentRequestUpdate withShippingAddress(PaymentAddress shippingAddress) {
        this.shippingAddress = shippingAddress;
        return this;
    }

    /**
     * Get the shippingOption value.
     *
     * @return the shippingOption value
     */
    public String shippingOption() {
        return this.shippingOption;
    }

    /**
     * Set the shippingOption value.
     *
     * @param shippingOption the shippingOption value to set
     * @return the PaymentRequestUpdate object itself.
     */
    public PaymentRequestUpdate withShippingOption(String shippingOption) {
        this.shippingOption = shippingOption;
        return this;
    }

}
