/**
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package com.microsoft.bot.schema.models;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * A PaymentResponse is returned when a user has selected a payment method and
 * approved a payment request.
 */
public class PaymentResponse {
    /**
     * The payment method identifier for the payment method that the user
     * selected to fulfil the transaction.
     */
    @JsonProperty(value = "methodName")
    private String methodName;

    /**
     * A JSON-serializable object that provides a payment method specific
     * message used by the merchant to process the transaction and determine
     * successful fund transfer.
     */
    @JsonProperty(value = "details")
    private Object details;

    /**
     * If the requestShipping flag was set to true in the PaymentOptions passed
     * to the PaymentRequest constructor, then shippingAddress will be the full
     * and final shipping address chosen by the user.
     */
    @JsonProperty(value = "shippingAddress")
    private PaymentAddress shippingAddress;

    /**
     * If the requestShipping flag was set to true in the PaymentOptions passed
     * to the PaymentRequest constructor, then shippingOption will be the id
     * attribute of the selected shipping option.
     */
    @JsonProperty(value = "shippingOption")
    private String shippingOption;

    /**
     * If the requestPayerEmail flag was set to true in the PaymentOptions
     * passed to the PaymentRequest constructor, then payerEmail will be the
     * email address chosen by the user.
     */
    @JsonProperty(value = "payerEmail")
    private String payerEmail;

    /**
     * If the requestPayerPhone flag was set to true in the PaymentOptions
     * passed to the PaymentRequest constructor, then payerPhone will be the
     * phone number chosen by the user.
     */
    @JsonProperty(value = "payerPhone")
    private String payerPhone;

    /**
     * Get the methodName value.
     *
     * @return the methodName value
     */
    public String methodName() {
        return this.methodName;
    }

    /**
     * Set the methodName value.
     *
     * @param methodName the methodName value to set
     * @return the PaymentResponse object itself.
     */
    public PaymentResponse withMethodName(String methodName) {
        this.methodName = methodName;
        return this;
    }

    /**
     * Get the details value.
     *
     * @return the details value
     */
    public Object details() {
        return this.details;
    }

    /**
     * Set the details value.
     *
     * @param details the details value to set
     * @return the PaymentResponse object itself.
     */
    public PaymentResponse withDetails(Object details) {
        this.details = details;
        return this;
    }

    /**
     * Get the shippingAddress value.
     *
     * @return the shippingAddress value
     */
    public PaymentAddress shippingAddress() {
        return this.shippingAddress;
    }

    /**
     * Set the shippingAddress value.
     *
     * @param shippingAddress the shippingAddress value to set
     * @return the PaymentResponse object itself.
     */
    public PaymentResponse withShippingAddress(PaymentAddress shippingAddress) {
        this.shippingAddress = shippingAddress;
        return this;
    }

    /**
     * Get the shippingOption value.
     *
     * @return the shippingOption value
     */
    public String shippingOption() {
        return this.shippingOption;
    }

    /**
     * Set the shippingOption value.
     *
     * @param shippingOption the shippingOption value to set
     * @return the PaymentResponse object itself.
     */
    public PaymentResponse withShippingOption(String shippingOption) {
        this.shippingOption = shippingOption;
        return this;
    }

    /**
     * Get the payerEmail value.
     *
     * @return the payerEmail value
     */
    public String payerEmail() {
        return this.payerEmail;
    }

    /**
     * Set the payerEmail value.
     *
     * @param payerEmail the payerEmail value to set
     * @return the PaymentResponse object itself.
     */
    public PaymentResponse withPayerEmail(String payerEmail) {
        this.payerEmail = payerEmail;
        return this;
    }

    /**
     * Get the payerPhone value.
     *
     * @return the payerPhone value
     */
    public String payerPhone() {
        return this.payerPhone;
    }

    /**
     * Set the payerPhone value.
     *
     * @param payerPhone the payerPhone value to set
     * @return the PaymentResponse object itself.
     */
    public PaymentResponse withPayerPhone(String payerPhone) {
        this.payerPhone = payerPhone;
        return this;
    }

}
