/**
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package com.microsoft.bot.schema.models;

import java.util.List;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * A receipt card.
 */
public class ReceiptCard {
    /**
     * Title of the card.
     */
    @JsonProperty(value = "title")
    private String title;

    /**
     * Array of Receipt Items.
     */
    @JsonProperty(value = "items")
    private List<ReceiptItem> items;

    /**
     * Array of Fact Objects   Array of key-value pairs.
     */
    @JsonProperty(value = "facts")
    private List<Fact> facts;

    /**
     * This action will be activated when user taps on the card.
     */
    @JsonProperty(value = "tap")
    private CardAction tap;

    /**
     * Total amount of money paid (or should be paid).
     */
    @JsonProperty(value = "total")
    private String total;

    /**
     * Total amount of TAX paid(or should be paid).
     */
    @JsonProperty(value = "tax")
    private String tax;

    /**
     * Total amount of VAT paid(or should be paid).
     */
    @JsonProperty(value = "vat")
    private String vat;

    /**
     * Set of actions applicable to the current card.
     */
    @JsonProperty(value = "buttons")
    private List<CardAction> buttons;

    /**
     * Get the title value.
     *
     * @return the title value
     */
    public String title() {
        return this.title;
    }

    /**
     * Set the title value.
     *
     * @param title the title value to set
     * @return the ReceiptCard object itself.
     */
    public ReceiptCard withTitle(String title) {
        this.title = title;
        return this;
    }

    /**
     * Get the items value.
     *
     * @return the items value
     */
    public List<ReceiptItem> items() {
        return this.items;
    }

    /**
     * Set the items value.
     *
     * @param items the items value to set
     * @return the ReceiptCard object itself.
     */
    public ReceiptCard withItems(List<ReceiptItem> items) {
        this.items = items;
        return this;
    }

    /**
     * Get the facts value.
     *
     * @return the facts value
     */
    public List<Fact> facts() {
        return this.facts;
    }

    /**
     * Set the facts value.
     *
     * @param facts the facts value to set
     * @return the ReceiptCard object itself.
     */
    public ReceiptCard withFacts(List<Fact> facts) {
        this.facts = facts;
        return this;
    }

    /**
     * Get the tap value.
     *
     * @return the tap value
     */
    public CardAction tap() {
        return this.tap;
    }

    /**
     * Set the tap value.
     *
     * @param tap the tap value to set
     * @return the ReceiptCard object itself.
     */
    public ReceiptCard withTap(CardAction tap) {
        this.tap = tap;
        return this;
    }

    /**
     * Get the total value.
     *
     * @return the total value
     */
    public String total() {
        return this.total;
    }

    /**
     * Set the total value.
     *
     * @param total the total value to set
     * @return the ReceiptCard object itself.
     */
    public ReceiptCard withTotal(String total) {
        this.total = total;
        return this;
    }

    /**
     * Get the tax value.
     *
     * @return the tax value
     */
    public String tax() {
        return this.tax;
    }

    /**
     * Set the tax value.
     *
     * @param tax the tax value to set
     * @return the ReceiptCard object itself.
     */
    public ReceiptCard withTax(String tax) {
        this.tax = tax;
        return this;
    }

    /**
     * Get the vat value.
     *
     * @return the vat value
     */
    public String vat() {
        return this.vat;
    }

    /**
     * Set the vat value.
     *
     * @param vat the vat value to set
     * @return the ReceiptCard object itself.
     */
    public ReceiptCard withVat(String vat) {
        this.vat = vat;
        return this;
    }

    /**
     * Get the buttons value.
     *
     * @return the buttons value
     */
    public List<CardAction> buttons() {
        return this.buttons;
    }

    /**
     * Set the buttons value.
     *
     * @param buttons the buttons value to set
     * @return the ReceiptCard object itself.
     */
    public ReceiptCard withButtons(List<CardAction> buttons) {
        this.buttons = buttons;
        return this;
    }

}
