/**
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package com.microsoft.bot.schema.models;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Refers to a substring of content within another field.
 */
public class TextHighlight {
    /**
     * Defines the snippet of text to highlight.
     */
    @JsonProperty(value = "text")
    private String text;

    /**
     * Occurrence of the text field within the referenced text, if multiple exist.
     */
    @JsonProperty(value = "occurence")
    private Integer occurence;

    /**
     * Get the text value.
     *
     * @return the text value
     */
    public String text() {
        return this.text;
    }

    /**
     * Set the text value.
     *
     * @param text the text value to set
     * @return the TextHighlight object itself.
     */
    public TextHighlight withText(String text) {
        this.text = text;
        return this;
    }

    /**
     * Get the occurence value.
     *
     * @return the occurence value
     */
    public Integer occurence() {
        return this.occurence;
    }

    /**
     * Set the occurence value.
     *
     * @param occurence the occurence value to set
     * @return the TextHighlight object itself.
     */
    public TextHighlight withOccurence(Integer occurence) {
        this.occurence = occurence;
        return this;
    }

}
