/**
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package com.microsoft.bot.schema.models;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Defines values for TextFormatTypes.
 */
public enum TextFormatTypes {
    /** Enum value markdown. */
    MARKDOWN("markdown"),

    /** Enum value plain. */
    PLAIN("plain"),

    /** Enum value xml. */
    XML("xml");

    /** The actual serialized value for a TextFormatTypes instance. */
    private String value;

    TextFormatTypes(String value) {
        this.value = value;
    }

    /**
     * Parses a serialized value to a TextFormatTypes instance.
     *
     * @param value the serialized value to parse.
     * @return the parsed TextFormatTypes object, or null if unable to parse.
     */
    @JsonCreator
    public static TextFormatTypes fromString(String value) {
        TextFormatTypes[] items = TextFormatTypes.values();
        for (TextFormatTypes item : items) {
            if (item.toString().equalsIgnoreCase(value)) {
                return item;
            }
        }
        return null;
    }

    @JsonValue
    @Override
    public String toString() {
        return this.value;
    }
}
