/**
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package com.microsoft.bot.schema.models;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Thing (entity type: "https://schema.org/Thing").
 */
public class Thing {
    /**
     * The type of the thing.
     */
    @JsonProperty(value = "type")
    private String type;

    /**
     * The name of the thing.
     */
    @JsonProperty(value = "name")
    private String name;

    /**
     * Get the type value.
     *
     * @return the type value
     */
    public String type() {
        return this.type;
    }

    /**
     * Set the type value.
     *
     * @param type the type value to set
     * @return the Thing object itself.
     */
    public Thing withType(String type) {
        this.type = type;
        return this;
    }

    /**
     * Get the name value.
     *
     * @return the name value
     */
    public String name() {
        return this.name;
    }

    /**
     * Set the name value.
     *
     * @param name the name value to set
     * @return the Thing object itself.
     */
    public Thing withName(String name) {
        this.name = name;
        return this;
    }

}
