/**
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package com.microsoft.bot.schema.models;

import java.util.Map;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * A request to receive a user token.
 */
public class TokenRequest {
    /**
     * The provider to request a user token from.
     */
    @JsonProperty(value = "provider")
    private String provider;

    /**
     * A collection of settings for the specific provider for this request.
     */
    @JsonProperty(value = "settings")
    private Map<String, Object> settings;

    /**
     * Get the provider value.
     *
     * @return the provider value
     */
    public String provider() {
        return this.provider;
    }

    /**
     * Set the provider value.
     *
     * @param provider the provider value to set
     * @return the TokenRequest object itself.
     */
    public TokenRequest withProvider(String provider) {
        this.provider = provider;
        return this;
    }

    /**
     * Get the settings value.
     *
     * @return the settings value
     */
    public Map<String, Object> settings() {
        return this.settings;
    }

    /**
     * Set the settings value.
     *
     * @param settings the settings value to set
     * @return the TokenRequest object itself.
     */
    public TokenRequest withSettings(Map<String, Object> settings) {
        this.settings = settings;
        return this;
    }

}
