/**
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package com.microsoft.bot.connector;

import java.util.Collection;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.microsoft.rest.ExpandableStringEnum;

/**
 * Defines values for ActivityImportance.
 */
public final class ActivityImportance extends ExpandableStringEnum<ActivityImportance> {
    /** Static value low for ActivityImportance. */
    public static final ActivityImportance LOW = fromString("low");

    /** Static value normal for ActivityImportance. */
    public static final ActivityImportance NORMAL = fromString("normal");

    /** Static value high for ActivityImportance. */
    public static final ActivityImportance HIGH = fromString("high");

    /**
     * Creates or finds a ActivityImportance from its string representation.
     * @param name a name to look for
     * @return the corresponding ActivityImportance
     */
    @JsonCreator
    public static ActivityImportance fromString(String name) {
        return fromString(name, ActivityImportance.class);
    }

    /**
     * @return known ActivityImportance values
     */
    public static Collection<ActivityImportance> values() {
        return values(ActivityImportance.class);
    }
}
