/**
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package com.microsoft.bot.connector;

import java.util.Collection;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.microsoft.rest.ExpandableStringEnum;

/**
 * Defines values for ActionTypes.
 */
public final class ActionTypes extends ExpandableStringEnum<ActionTypes> {
    /** Static value openUrl for ActionTypes. */
    public static final ActionTypes OPEN_URL = fromString("openUrl");

    /** Static value imBack for ActionTypes. */
    public static final ActionTypes IM_BACK = fromString("imBack");

    /** Static value postBack for ActionTypes. */
    public static final ActionTypes POST_BACK = fromString("postBack");

    /** Static value playAudio for ActionTypes. */
    public static final ActionTypes PLAY_AUDIO = fromString("playAudio");

    /** Static value playVideo for ActionTypes. */
    public static final ActionTypes PLAY_VIDEO = fromString("playVideo");

    /** Static value showImage for ActionTypes. */
    public static final ActionTypes SHOW_IMAGE = fromString("showImage");

    /** Static value downloadFile for ActionTypes. */
    public static final ActionTypes DOWNLOAD_FILE = fromString("downloadFile");

    /** Static value signin for ActionTypes. */
    public static final ActionTypes SIGNIN = fromString("signin");

    /** Static value call for ActionTypes. */
    public static final ActionTypes CALL = fromString("call");

    /** Static value payment for ActionTypes. */
    public static final ActionTypes PAYMENT = fromString("payment");

    /** Static value messageBack for ActionTypes. */
    public static final ActionTypes MESSAGE_BACK = fromString("messageBack");

    /**
     * Creates or finds a ActionTypes from its string representation.
     * @param name a name to look for
     * @return the corresponding ActionTypes
     */
    @JsonCreator
    public static ActionTypes fromString(String name) {
        return fromString(name, ActionTypes.class);
    }

    /**
     * @return known ActionTypes values
     */
    public static Collection<ActionTypes> values() {
        return values(ActionTypes.class);
    }
}
