/**
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package com.microsoft.bot.connector;

import java.util.Collection;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.microsoft.rest.ExpandableStringEnum;

/**
 * Defines values for AttachmentLayoutTypes.
 */
public final class AttachmentLayoutTypes extends ExpandableStringEnum<AttachmentLayoutTypes> {
    /** Static value list for AttachmentLayoutTypes. */
    public static final AttachmentLayoutTypes LIST = fromString("list");

    /** Static value carousel for AttachmentLayoutTypes. */
    public static final AttachmentLayoutTypes CAROUSEL = fromString("carousel");

    /**
     * Creates or finds a AttachmentLayoutTypes from its string representation.
     * @param name a name to look for
     * @return the corresponding AttachmentLayoutTypes
     */
    @JsonCreator
    public static AttachmentLayoutTypes fromString(String name) {
        return fromString(name, AttachmentLayoutTypes.class);
    }

    /**
     * @return known AttachmentLayoutTypes values
     */
    public static Collection<AttachmentLayoutTypes> values() {
        return values(AttachmentLayoutTypes.class);
    }
}
