/**
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package com.microsoft.bot.connector;

import com.microsoft.rest.RestClient;

/**
 * The interface for ConnectorClient class.
 */
public interface ConnectorClient {
    /**
     * Gets the REST client.
     *
     * @return the {@link RestClient} object.
    */
    RestClient restClient();

    /**
     * The default base URL.
     */
    String DEFAULT_BASE_URL = "https://api.botframework.com";

    /**
     * Gets the Attachments object to access its operations.
     * @return the Attachments object.
     */
    Attachments attachments();

    /**
     * Gets the Conversations object to access its operations.
     * @return the Conversations object.
     */
    Conversations conversations();

}
