/**
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package com.microsoft.bot.connector;

import java.util.Collection;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.microsoft.rest.ExpandableStringEnum;

/**
 * Defines values for ContactRelationUpdateActionTypes.
 */
public final class ContactRelationUpdateActionTypes extends ExpandableStringEnum<ContactRelationUpdateActionTypes> {
    /** Static value add for ContactRelationUpdateActionTypes. */
    public static final ContactRelationUpdateActionTypes ADD = fromString("add");

    /** Static value remove for ContactRelationUpdateActionTypes. */
    public static final ContactRelationUpdateActionTypes REMOVE = fromString("remove");

    /**
     * Creates or finds a ContactRelationUpdateActionTypes from its string representation.
     * @param name a name to look for
     * @return the corresponding ContactRelationUpdateActionTypes
     */
    @JsonCreator
    public static ContactRelationUpdateActionTypes fromString(String name) {
        return fromString(name, ContactRelationUpdateActionTypes.class);
    }

    /**
     * @return known ContactRelationUpdateActionTypes values
     */
    public static Collection<ContactRelationUpdateActionTypes> values() {
        return values(ContactRelationUpdateActionTypes.class);
    }
}
