/**
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package com.microsoft.bot.connector;

import java.util.Collection;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.microsoft.rest.ExpandableStringEnum;

/**
 * Defines values for EndOfConversationCodes.
 */
public final class EndOfConversationCodes extends ExpandableStringEnum<EndOfConversationCodes> {
    /** Static value unknown for EndOfConversationCodes. */
    public static final EndOfConversationCodes UNKNOWN = fromString("unknown");

    /** Static value completedSuccessfully for EndOfConversationCodes. */
    public static final EndOfConversationCodes COMPLETED_SUCCESSFULLY = fromString("completedSuccessfully");

    /** Static value userCancelled for EndOfConversationCodes. */
    public static final EndOfConversationCodes USER_CANCELLED = fromString("userCancelled");

    /** Static value botTimedOut for EndOfConversationCodes. */
    public static final EndOfConversationCodes BOT_TIMED_OUT = fromString("botTimedOut");

    /** Static value botIssuedInvalidMessage for EndOfConversationCodes. */
    public static final EndOfConversationCodes BOT_ISSUED_INVALID_MESSAGE = fromString("botIssuedInvalidMessage");

    /** Static value channelFailed for EndOfConversationCodes. */
    public static final EndOfConversationCodes CHANNEL_FAILED = fromString("channelFailed");

    /**
     * Creates or finds a EndOfConversationCodes from its string representation.
     * @param name a name to look for
     * @return the corresponding EndOfConversationCodes
     */
    @JsonCreator
    public static EndOfConversationCodes fromString(String name) {
        return fromString(name, EndOfConversationCodes.class);
    }

    /**
     * @return known EndOfConversationCodes values
     */
    public static Collection<EndOfConversationCodes> values() {
        return values(EndOfConversationCodes.class);
    }
}
