/**
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package com.microsoft.bot.connector;

import java.util.Collection;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.microsoft.rest.ExpandableStringEnum;

/**
 * Defines values for InputHints.
 */
public final class InputHints extends ExpandableStringEnum<InputHints> {
    /** Static value acceptingInput for InputHints. */
    public static final InputHints ACCEPTING_INPUT = fromString("acceptingInput");

    /** Static value ignoringInput for InputHints. */
    public static final InputHints IGNORING_INPUT = fromString("ignoringInput");

    /** Static value expectingInput for InputHints. */
    public static final InputHints EXPECTING_INPUT = fromString("expectingInput");

    /**
     * Creates or finds a InputHints from its string representation.
     * @param name a name to look for
     * @return the corresponding InputHints
     */
    @JsonCreator
    public static InputHints fromString(String name) {
        return fromString(name, InputHints.class);
    }

    /**
     * @return known InputHints values
     */
    public static Collection<InputHints> values() {
        return values(InputHints.class);
    }
}
