/**
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package com.microsoft.bot.connector;

import java.util.Collection;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.microsoft.rest.ExpandableStringEnum;

/**
 * Defines values for MessageReactionTypes.
 */
public final class MessageReactionTypes extends ExpandableStringEnum<MessageReactionTypes> {
    /** Static value like for MessageReactionTypes. */
    public static final MessageReactionTypes LIKE = fromString("like");

    /** Static value plusOne for MessageReactionTypes. */
    public static final MessageReactionTypes PLUS_ONE = fromString("plusOne");

    /**
     * Creates or finds a MessageReactionTypes from its string representation.
     * @param name a name to look for
     * @return the corresponding MessageReactionTypes
     */
    @JsonCreator
    public static MessageReactionTypes fromString(String name) {
        return fromString(name, MessageReactionTypes.class);
    }

    /**
     * @return known MessageReactionTypes values
     */
    public static Collection<MessageReactionTypes> values() {
        return values(MessageReactionTypes.class);
    }
}
