/**
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package com.microsoft.bot.connector;

import java.util.List;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * W3C Payment Method Data for Microsoft Pay.
 */
public class MicrosoftPayMethodData {
    /**
     * Microsoft Pay Merchant ID.
     */
    @JsonProperty(value = "mechantId")
    private String mechantId;

    /**
     * Supported payment networks (e.g., "visa" and "mastercard").
     */
    @JsonProperty(value = "supportedNetworks")
    private List<String> supportedNetworks;

    /**
     * Supported payment types (e.g., "credit").
     */
    @JsonProperty(value = "supportedTypes")
    private List<String> supportedTypes;

    /**
     * Get the mechantId value.
     *
     * @return the mechantId value
     */
    public String mechantId() {
        return this.mechantId;
    }

    /**
     * Set the mechantId value.
     *
     * @param mechantId the mechantId value to set
     * @return the MicrosoftPayMethodData object itself.
     */
    public MicrosoftPayMethodData withMechantId(String mechantId) {
        this.mechantId = mechantId;
        return this;
    }

    /**
     * Get the supportedNetworks value.
     *
     * @return the supportedNetworks value
     */
    public List<String> supportedNetworks() {
        return this.supportedNetworks;
    }

    /**
     * Set the supportedNetworks value.
     *
     * @param supportedNetworks the supportedNetworks value to set
     * @return the MicrosoftPayMethodData object itself.
     */
    public MicrosoftPayMethodData withSupportedNetworks(List<String> supportedNetworks) {
        this.supportedNetworks = supportedNetworks;
        return this;
    }

    /**
     * Get the supportedTypes value.
     *
     * @return the supportedTypes value
     */
    public List<String> supportedTypes() {
        return this.supportedTypes;
    }

    /**
     * Set the supportedTypes value.
     *
     * @param supportedTypes the supportedTypes value to set
     * @return the MicrosoftPayMethodData object itself.
     */
    public MicrosoftPayMethodData withSupportedTypes(List<String> supportedTypes) {
        this.supportedTypes = supportedTypes;
        return this;
    }

}
