/**
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package com.microsoft.bot.connector;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * A result object from a Payment Request Update invoke operation.
 */
public class PaymentRequestUpdateResult {
    /**
     * Update payment details.
     */
    @JsonProperty(value = "details")
    private PaymentDetails details;

    /**
     * Get the details value.
     *
     * @return the details value
     */
    public PaymentDetails details() {
        return this.details;
    }

    /**
     * Set the details value.
     *
     * @param details the details value to set
     * @return the PaymentRequestUpdateResult object itself.
     */
    public PaymentRequestUpdateResult withDetails(PaymentDetails details) {
        this.details = details;
        return this;
    }

}
