/**
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package com.microsoft.bot.connector;

import java.util.Collection;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.microsoft.rest.ExpandableStringEnum;

/**
 * Defines values for TextFormatTypes.
 */
public final class TextFormatTypes extends ExpandableStringEnum<TextFormatTypes> {
    /** Static value markdown for TextFormatTypes. */
    public static final TextFormatTypes MARKDOWN = fromString("markdown");

    /** Static value plain for TextFormatTypes. */
    public static final TextFormatTypes PLAIN = fromString("plain");

    /** Static value xml for TextFormatTypes. */
    public static final TextFormatTypes XML = fromString("xml");

    /**
     * Creates or finds a TextFormatTypes from its string representation.
     * @param name a name to look for
     * @return the corresponding TextFormatTypes
     */
    @JsonCreator
    public static TextFormatTypes fromString(String name) {
        return fromString(name, TextFormatTypes.class);
    }

    /**
     * @return known TextFormatTypes values
     */
    public static Collection<TextFormatTypes> values() {
        return values(TextFormatTypes.class);
    }
}
