/**
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package com.microsoft.bot.connector;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Thumbnail URL.
 */
public class ThumbnailUrl {
    /**
     * URL pointing to the thumbnail to use for media content.
     */
    @JsonProperty(value = "url", required = true)
    private String url;

    /**
     * HTML alt text to include on this thumbnail image.
     */
    @JsonProperty(value = "alt")
    private String alt;

    /**
     * Get the url value.
     *
     * @return the url value
     */
    public String url() {
        return this.url;
    }

    /**
     * Set the url value.
     *
     * @param url the url value to set
     * @return the ThumbnailUrl object itself.
     */
    public ThumbnailUrl withUrl(String url) {
        this.url = url;
        return this;
    }

    /**
     * Get the alt value.
     *
     * @return the alt value
     */
    public String alt() {
        return this.alt;
    }

    /**
     * Set the alt value.
     *
     * @param alt the alt value to set
     * @return the ThumbnailUrl object itself.
     */
    public ThumbnailUrl withAlt(String alt) {
        this.alt = alt;
        return this;
    }

}
